### ISSUE TITLE
    aligner = pybel.ob.OBAlign() AttributeError: module 'openbabel.openbabel' has no attribute 'OBAlig

### ISSUE THREAD

**Issue by WT1991CADD** [isayevlab/Auto3D_pkg#23] opened 2022-10-12 08:56 UTC
Dear author

When I run the program, a bug occurred, how I solve this problem "   

 aligner = pybel.ob.OBAlign() 
AttributeError: module 'openbabel.openbabel' has no attribute 'OBAlig"
“. 

Thanks for your help

**Comment by WT1991CADD** [comment] 2022-10-13 00:40
Thanks for your reply. 
My Python version is "3.9.12", and  openbabel version is 3.1.1.1. However, the error still report as above mentioned.

**Comment by LiuCMU** [comment] 2022-10-13 01:30
Thank you for the feedback!

This is interesting.  To make sure your openbabel and auto3d are in the same environment, could you try the following commands in your terminal and share the output?
```
conda list Auto3D   
conda list openbabel
python    
from openbabel import pybel
aligner = pybel.ob.OBAlign()
```
The output will help me to reproduce your bug and figure out what is going on.  Thanks!


Here is my output when trying the above commands:
```
(py39) liu5$conda list Auto3D   
# packages in environment at /opt/anaconda3/envs/py39:
#
# Name                    Version                   Build  Channel
auto3d                    1.13                     pypi_0    pypi
(py39) liu5$conda list openbabel
# packages in environment at /opt/anaconda3/envs/py39:
#
# Name                    Version                   Build  Channel
openbabel                 3.1.1            py39hb4f85b1_4    conda-forge
(py39) liu5$python
Python 3.9.13 (main, Aug 25 2022, 18:29:29) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from openbabel import pybel
>>> aligner = pybel.ob.OBAlign()
>>> 
```

**Comment by WT1991CADD** [comment] 2022-10-13 03:15
Thanks for your kindly suggestions. I have reinstall the software as the tutorial you writed and the software works. The  error I mentioned above possible due to I use the virtualenv software to conduct the environment.

**Comment by LiuCMU** [comment] 2022-10-13 12:23
Great to know that it worked out! Thanks for supporting Auto3D. Since the issue is solved, I will close it for now.  Feel free to open issues if you have further questions.

**Closed by LiuCMU** 2022-10-13 12:23 UTC
